### ISSUE TITLE
Elements visible after joining a battleground while mounted

### ISSUE THREAD

**Issue by alanpaulprice** [keyboardturner/DragonRider#2]
I thought this might be a default UI bug, but it didn't happen when I disabled Dragon Rider. Might be a coincidence. I'll update this comment if I do reproduce it with Dragon Rider disabled.

![image](https://github.com/user-attachments/assets/80c0d033-977b-4f6f-b793-a113aa1da275)

**Comment by keyboardturner** [comment]
will look into it, this *might* be a Blizzard bug that caused it but the code handling the models is pretty bad/old anyway so it'll likely get a redesign next update

**Comment by keyboardturner** [comment]
this _should_ be resolved with update 0.4.6, at least to my testing with Comp Stomp week
